# See https://babelizer.readthedocs.io/ for more information

# Describe the library being wrapped.
[library.WOFOST]
language = "c"
library = "bmiwofost"
header = "bmi_wofost.h"
entry_point = "register_bmi_wofost"

# Describe compiler options need to build the library being wrapped.
[build]

# Describe the newly wrapped package.
[package]
name = "pymt_wofost"
requirements = ["bmi-c", "libnetcdf"]

[info]
github_username = "BramDr"
package_author = "Bram Droppers"
package_author_email = "bram.droppers@gmail.com"
package_license = "GNU General Public License v3"
summary = "PyMT component for the C WOFOST model with a Basic Model Interface implementation"

[ci]
python_version = ["3.14"]
os = ["linux"]