# Configuration file for running the WOFOST crop model with BMI

# Common meteorology section
START_DATE              1980-01-01
END_DATE                1980-12-31
BMI_COUPLING            STANDALONE
IGNORE_NUTRIENT_STRESS  FALSE
IGNORE_SOIL_MOISTURE    FALSE
OUTPUT_DIRECTORY        ci/output
STATE_DIRECTORY         ci/state
AREA_FILE               ci/data/domain/vegetation_fraction_maize_irrigated_2000_05min_conus.nc                          Band1
WEATHER_FILE            TMIN        ci/data/forcing/05min/conus/gfdl-esm4_r1i1p1f1_w5e5_historical_tasmin_global_daily_1980.nc      tasmin      KELVIN
WEATHER_FILE            TMAX        ci/data/forcing/05min/conus/gfdl-esm4_r1i1p1f1_w5e5_historical_tasmax_global_daily_1980.nc      tasmax      KELVIN
WEATHER_FILE            RADIATION   ci/data/forcing/05min/conus/gfdl-esm4_r1i1p1f1_w5e5_historical_rsds_global_daily_1980.nc        rsds        W_PER_M2
WEATHER_FILE            RAIN        ci/data/forcing/05min/conus/gfdl-esm4_r1i1p1f1_w5e5_historical_pr_global_daily_1980.nc          pr          KG_PER_M2_PER_S
WEATHER_FILE            WINDSPEED   ci/data/forcing/05min/conus/gfdl-esm4_r1i1p1f1_w5e5_historical_sfcwind_global_daily_1980.nc     sfcwind     M_PER_S
WEATHER_FILE            VAPOUR      ci/data/forcing/05min/conus/gfdl-esm4_r1i1p1f1_w5e5_historical_vp_global_daily_1980.nc          vp          HPA

# Maize crop
CROP_NAME       maize
PLANT_DATE      1
EMERGENCE       0
CROP_FILE       ci/data/crop/mag201.cab
MANAGEMENT_FILE ci/data/management/rb_mg.dat
SOIL_FILE       ci/data/soil/ec4.new
SITE_FILE       ci/data/site/rb.site
DOMAIN_FILE     MASK        ci/data/domain/vegetation_fraction_maize_irrigated_2000_05min_conus.nc     Band1
DOMAIN_FILE     PLANT_DATE  ci/data/parameters/Maize_cc_conus_irrigated_5min.nc                        Band1
OUTPUT_TYPE     GROWTH_DAY
OUTPUT_TYPE     DEVELOPMENT
OUTPUT_TYPE     STORAGE_BIOMASS
OUTPUT_TYPE     WATER_STRESS
OUTPUT_TYPE     HEAT_STRESS
OUTPUT_TYPE     NUTRIENT_STRESS

# Wheat crop
CROP_NAME       wheat
PLANT_DATE      1
EMERGENCE       0
CROP_FILE       ci/data/crop/wwh102.cab
MANAGEMENT_FILE ci/data/management/rb_mg.dat
SOIL_FILE       ci/data/soil/ec4.new
SITE_FILE       ci/data/site/rb.site
DOMAIN_FILE     MASK        ci/data/domain/vegetation_fraction_wheat_irrigated_2000_05min_conus.nc     Band1
DOMAIN_FILE     PLANT_DATE  ci/data/parameters/Wheat_cc_conus_irrigated_5min.nc                        Band1
OUTPUT_TYPE     GROWTH_DAY
OUTPUT_TYPE     DEVELOPMENT
OUTPUT_TYPE     STORAGE_BIOMASS
OUTPUT_TYPE     WATER_STRESS
OUTPUT_TYPE     HEAT_STRESS
OUTPUT_TYPE     NUTRIENT_STRESS
